---
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    modules: true

env:
  browser: true
  commonjs: true
  node: true
  es6: true
  amd: false

extends:
  - eslint:recommended
  - plugin:react/recommended

rules:
  no-console: off
  strict:
    - error
    - global
  curly: warn